apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms1
  template:
    metadata:
      labels:
        app: ms1
    spec:
      containers:
      - name: ms1
        image: kubeaziz/ms1:v1    
        ports:
        - containerPort: 3000
